lang: fr

project: 
  title: "Iconic Security"
  type: website
  output-dir: docs/fr

website:
  page-navigation: true
  title: "Accueil"
  site-url: "https://kkhurana007.github.io/iconic-security/fr/"
  page-footer:
    left: "Cite web créer avec [Quarto](https://quarto.org/) par [Kunal](https://ilovesoils.com/about.html)."

    right:
      - text: English
        href: https://kkhurana007.github.io/iconic-security/
      - text: Français
        href: https://kkhurana007.github.io/iconic-security/fr/
      - icon: envelope
        href: mailto:info@iconicsecurity.ca
      - text: "@2024 Iconic Security. Tous droits réservés."
  navbar:
    left:
      - text: "À propos"
        href: about.qmd
      - text: "Nos Services"
        href: services.qmd 
      - text: "Emplois"
        href: careers.qmd       
      - text: "Pourquoi nous choisir?"
        href: choose.qmd
      - text: "Nous Contacter"
        href: contact.qmd
    right:
      - href: https://kkhurana007.github.io/iconic-security/
        text: English
      - href: https://kkhurana007.github.io/iconic-security/fr/
        text: Français 