lang: en

project: 
  title: "Iconic Security"
  type: website
  output-dir: docs


website:
  page-navigation: true
  title: "Homepage"
  site-url: "https://kkhurana007.github.io/iconic-security/"
  page-footer:
    left: "Website made with [Quarto](https://quarto.org/) by [Kunal](https://ilovesoils.com/about.html)."

    right:
      - text: English
        href: https://kkhurana007.github.io/iconic-security/
      - text: Français
        href: https://kkhurana007.github.io/iconic-security/fr/
      - icon: envelope
        href: mailto:info@iconicsecurity.ca
      - text: "@2024 Iconic Security. All rights reserved."


  #search:
    #location: navbar
    #type: overlay
    
  navbar:
    left:
      - text: "About Us"
        href: about.qmd
      - text: "Our Services"
        href: services.qmd
      - text: "Careers"
        href: careers.qmd        
      - text: "Why Choose us?"
        href: choose.qmd
      - text: "Contact Us"
        href: contact.qmd
    right:
      - href: https://kkhurana007.github.io/iconic-security/
        text: English
      - href: https://kkhurana007.github.io/iconic-security/fr/
        text: Français 

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual


execute:
  freeze: true
  #increment: true